name: Build PDFs and Update Dashboard

on:
  schedule:
    # UTC time — change to when you want it to run
    - cron: "30 6 * * *"
  workflow_dispatch: {}   # lets you run it manually

permissions:
  contents: write          # so the bot can commit PDFs/index.html
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Update these script names if yours differ
      - name: Generate PDFs
        run: |
          python scrape_party_leaders.py
          python scrape_reform_mps.py

      - name: Rebuild index.html
        run: |
          python update_dashboard.py "."

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Automated: PDFs + index update [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

  # OPTIONAL: publish via GitHub Pages (delete this job if you don't need Pages)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
