name: Build PDFs and Update Dashboard

  on:
  push:
    branches: [ main ]          # run on any push to main
  # Every 30 minutes starting 06:30–16:00 UTC
  # (= 07:30–17:00 London while BST is in effect)
  schedule:
    - cron: "30 6-15 * * *"     # :30 at 06:30..15:30 UTC
    - cron: "0 7-16 * * *"      # :00 at 07:00..16:00 UTC
  workflow_dispatch: {}          # manual Run workflow button


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate PDFs
        run: |
          python partyleaders_mentions.py
          python reform_mps.py

      - name: Rebuild index.html
        run: |
          python update_dashboard.py "."

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Automated: PDFs + index update [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true   # ensures GitHub Pages is enabled

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
